sudo: false

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

cache:
  directories:
    - $HOME/.cache/pip

install:
  - pip install -U tox tox-travis pip wheel codecov

script:
  - tox

after_success:
  - codecov -e TOX_ENV

branches:
  only:
    - master
